import { InputEntry } from '@/services/types';

export const getEmptyInput = (selectedReportId: string): InputEntry => ({
  id: 'new',
  name: '',
  comment: '',
  report: selectedReportId,
  scope: 1,
  sum_value: 0,
  equivalent: null,
  category: null,
  facility: null,
  parent: null,
  raw_value: null as any,
  monthly_values: false,
  raw_value_jan: null as any,
  raw_value_feb: null as any,
  raw_value_mar: null as any,
  raw_value_apr: null as any,
  raw_value_may: null as any,
  raw_value_jun: null as any,
  raw_value_jul: null as any,
  raw_value_aug: null as any,
  raw_value_sep: null as any,
  raw_value_oct: null as any,
  raw_value_nov: null as any,
  raw_value_dec: null as any,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
});
