import { InputEntry } from '@/services/types';

export const getEmptyInput = (selectedReportId: string): InputEntry => ({
  id: 'new',
  name: '',
  comment: '',
  report: selectedReportId,
  scope: 1,
  sumValue: 0,
  equivalent: null,
  category: null,
  facility: null,
  parent: null,
  rawValue: null as any,
  monthlyValues: false,
  rawValueJan: null as any,
  rawValueFeb: null as any,
  rawValueMar: null as any,
  rawValueApr: null as any,
  rawValueMay: null as any,
  rawValueJun: null as any,
  rawValueJul: null as any,
  rawValueAug: null as any,
  rawValueSep: null as any,
  rawValueOct: null as any,
  rawValueNov: null as any,
  rawValueDec: null as any,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});
